github_username: "gdroos46"

projects:
  - name: "jreast"
    repo: "favy-jp/media.jrenet.jp"
  - name: "inak-system"
    repo: "launch-lab/inak-system"
  - name: "sanyo-sangyo-bs"
    repo: "launch-lab/sanyo-sangyo-bs"
  - name: "spine"
    repo: "launch-lab/spine-rails"
  # - name: "個人案件"
    # repo: "hataponnu/mensoku"
